# 20231030_02

---
課程：1121所得稅法一
日期：2023/10/30
周次：09
節次：2
---

最新的所得稅法第八條規定中華民國來源所得認定原則，修正日期是民國 112 年 10 月 13 日，台財稅字第11204568350號 令。
我們現在是10月30號，所以是17天以前。啊，我跟各位講啊，就是因為他這樣常常更新，所以實務上根本不可能考這個。因為你考可能立刻考題出來就過世。所以各位不要傻傻去倍增。這個沒意義，我只是透過這個跟各位講我們的法條規定，財政部可以自己就透過這個解釋令公布實際上變更。是不是中華民國來？ 判斷標準。實際上，決定課稅權限的大或小，你不覺得這樣符合依法課稅嗎？ 你如果在的。我跟你是不太一樣的感覺就是這樣。好，那我現在跟各位講一下財政部的這個解釋令，如果我沒有念錯的話，那原則上我不要每一個念，因為這個是一個，我認為很長，因為他總total就補液。剛剛有幾位同學來問。我跟各位說一下，我對這些原則哈，基本上就是立法低密度力。標準不明。然後這一些其政規則，因為他都沒有授權。他都會用事實認定標準的這種。法律形式出現啊，因為他在第一點裡面就沒有講我是從哪裡來的。如果有一般而言，法規命令會自己說，我是哪一個條文授權規定。這個都不會。啊，我們的稅籍居民那個也是一樣，他都不會講自己的，所以他在實務上呈現的態樣，都是用事實認定基準事實認定的標準。以行政規則的姿態出現，可是他實際上就決定了我們課稅權限到底有多少的所得的範圍，這個大概是這樣一個情形，那么接下來在實務上為什麼會到5月？你如果講要依法課稅，那就把這5頁的規定全部讓進去，所得稅把那個所得稅法的條款一個爆掉。清楚嗎？其實我們這樣講，在我們的實務上，常常是他該有的劃分標準沒出來，但不該有的劃分則是過度劃分，各位能明白那個意思嗎？就叫做過猶不及。法制落後國家的最通常現象往往不是他沒有法律，而是那個標準。那個區分界線在哪裡不清楚或者被清楚出來的規範，你認為他過猶不及？ 這是法治落後的很標準的現象，可是那個分寸抓不清楚。因此，法律者的任務就是。如果可能，我們當然透過法律解釋。啊，如果連法律解釋都做不到，我們就只能要改變立法啊，這個就是我跟各位去講過，其實法律人在稅法的領域有一些比較，我個人認為是蠻特殊的，因為我們是追求法治國。你任何萬千政策好意都要透過法規範來實現，不是你一個人說了怎麼算？ 因此，因此所有我們今天跟各位講的判準老師當然會希望說，欸最好？我們所得稅法第8人就這樣定，可是。不是老師一個人說了算，這個標準一定要入法，否則他的這個標準，他原則上他就會一直產生一種浮動不明而過猶不及，這種現象會不斷的發生。就這樣一個法治國家落後的現象，大概是這樣一個情形。也因此，我們提到這個地方跟各位去談的這個所得來源地的認定標準好，那我現在就因為他不是條所以用點的方式，因為這個實務上面他沒有協調，這也是另外一個，我常常實在是很受不了，財政部就是你你的那個就是不太知道事實立法二程序法，然後也不太知道你的稅捐，你的主體客體稅基稅率那個構成要件，他沒有那個清楚地分明。其實以我自己的了解，就是他們都是個別承辦的人。參考一個外國吧，然後就直接把抄過來，像做我一樣。像我一樣，所以你看到我們現在的條就是看起來像作文啊，就大概。這個就是實務上很常見的一各一各情況好，我確定第2點喔，因為第2點很長。他說，本法第8條第一款所稱就贏了很長一段話啊。這個一中華病毒公司法規定設立登記成立之公司或其中華民國政府認許在中華民國境內營業之外國公司所分配之股利好。這句話飲完以後，就想指依公司法規定，在中華民國境內設立登記之公司所分配之股利啊，這樣各位清楚了嗎？就是。依我國法。設立的公司，這個公司發放的主力，這個叫中華民國來源所得啊，這個就是我剛剛跟各位講的，這個叫準據法。因為你去辦公司登記的時候，他上面就會寫本公司是一公司法第幾條？ 設立的在哪裡？他上面就會寫，設立地點在哪裡啊？比如說在臺北市大安區幾號幾號啊，那你負責人是誰都會寫嗎？這個就是在實務上，總機構在中華民國境內。所以總機構在中華民國境內，我們往往我開一些教科書，有些會寫說，哦，我們有分三類，一種叫做實質管理處所，第一重叫做準據法的，而我們就不是實質管理處所，我們也不是準據法，我們叫總機構在中華民國境內。我都看不太懂，就好像我在看那個憲法意義講什麼叫均權原則按不是聯邦制，也不是單一制，我們兄弟獨厚是創建叫均權制好吧。不知道你在講。當然啦，看起來都符合一個事物，法則就是說軍爵原則是一事務之本質分類，凡是有歸中央者，要統一者則歸中央，凡是有個地方個別做不同，規定者就歸地方。廢話不是本來就應該如此。好，那如果不能決定的話，則由立法院決定，隻我告訴你就是這句話。這句話才真正表現，我們就是個單一國家。你不要只看前面那個，因為當中央跟地方有爭議的時候。立法院是誰的機構？ 是地方的嘛。他是中央的立法機構，所以我們就是一個徹頭徹尾的單一制國家。因為有決議就我說了算，我中央說了算。這就是一個很典型的，你不要只看那個名目的那個名稱，那同樣的道理就是在這個第2點裡面。其實他要講的就是依我國法設立的。從這個我國法設立的公司所發放的股利盈餘，這個就是我們的中華民國來源所得好。第2點裡面有一個但書的規定，但書的規定也就是第二句的規定哦就很。但中華民國來源所得這個部分不包括外國公司在中華民國境內設立之分公司的盈餘匯回好OK。如果是。依外國法設立在臺灣的分公司，也就是他是屬於外國公司。但在境內，他只是以分公司的型態當分公司把這個盈餘匯回去給他的總公司的時候，這個盈餘匯回不是為股利盈餘分配在中華民國境內來源所。他的條文規定是指說臺灣分公司會回去給外國總公司的這個股利，盈餘的會為不是中華民國來源所。這個條文規定，在我個人來看比較不太對。因為他的本意應該不是在講中華民國來源，而是指說分公司匯回給總公司的這一筆，不認為是股利盈餘。這個是客體的否認，而不是所得來源地的否認，對能夠知道老師在這裡講的意思嗎？他的概念應是說分公司把股利盈餘匯回去給境外的總公司，這一筆股利盈餘的會回。他不視為是一種鼓勵的分配。他是在否認他是股利分配的概念，而不是所得來源地的否認，各位。其實他還是中華民國匯出去的，只是他不是。股利盈餘。那我們的條規定是看起來有一點點說，這個不是中華民國來源所得啊，這個是第2點。第二句，但不包括外國公司在中華民國境內設立之分公司之盈餘會館啊，這個就是第2點。第二句。這個但書的規定好，第2點，接下來還有一個的。二段或者是第三句的規定好，依外國法律規定設立登記之外國公司，其經中華民國證券主管機關核準來臺募集與發行股票或臺灣存託憑證，並在中華民國證券交易市場掛牌買賣者，該外國公司所發行之鼓勵非屬中華民國來源所得。第三句的規定，他是在講tdr。臺灣存託憑證。美國或新加坡上市公司，他是在各該當的公開發行股份的公司。那么透過在本地在臺灣發行所謂的tdr，這個叫臺灣存託憑證。一股的臺灣存託憑證對應一個外國的股份。啊，對應一各新加坡或美國的股份。基本上tdr所謂的存托憑證，是一種叫衍生性金融商品。因為在各該美國跟新加坡都是在該地發行的有價證券，而你是有價證券的再次延伸。再次延伸你在新加坡上市的在美國納斯達克上市的，那你發行一個在臺灣以一定的比例去對應的外國公司股票，所以臺灣存託憑證是外國發行有價證券的衍生性金融商品。反之亦然，臺積電是在臺灣發行的公開發行股份的上市櫃公司，那麼他在美國的這個就叫存託憑證，至這個就叫做HDR。如果是全球範圍發行的，這個就叫global GDR。如果是在歐洲發行的這個資料一定要就這樣而已，他基本上對應的就是在本地公開發行的一個有價證券之衍生性金融商品。一般而言，這個價格會用一個比例的方式去做計算，然後在這個地方，一個ADR或TPR會對應一個在外國發行的一個所謂的有價證券。好，我們的第三句規定的意思是說。當發行在臺灣的存托憑證，那么你。透過外國公司所發給的股利盈餘，那麼透過tdr的方式因此而產生之股利盈餘的分配，則認為部屬中華民國來源所得，也就是他是屬於各該發行的國家的該地的來源所得，美國發起的就是美國來源所得，新加坡的就是新加坡，那臺灣的tdr這個部分，原則上這個就是一個在一個有價證券就是一個股權。衍生性金融商品或是債權的衍生性金融商品，這種衍生性商品則回到最初的他的。這個資本市場裡面由該地去課徵他們的所得稅，這個是第2點的第三句，他所想要表。也就是如果是存託憑證，是否是依照我國法律發行的十多憑證？不論只要你是這一類的，在後股票的衍生性商品的話，原則上回到他原先所聯繫的那個基礎證券來判斷他的所得來源地，這個是第2點的第三句，他所想要講。這個，請問一下，在我們所得稅法第8條第一款規定，有這個條文嗎？ 應該沒有吧？ 從哪裡得到的這個規範的依據呢？ 我也看不出來他到底是從哪裡來欸，有沒有道理呢？另外這個是另外其次的問題，在我自己個人來看，臺灣的tdr，如果臺灣的tdr，那臺灣的這個部分就是臺灣的那個所得。臺灣的tdr也就我們這個地方做股利盈餘的分配，我們雖然聯繫的是美國或是新加坡的一個上市櫃發行的股份沒有錯，他確實是這樣，這樣再回來臺灣衍生性金融商品的特色，就是他可以不斷延伸。不斷地延伸，你在美國發行了，他可以不斷地透過這種延伸的方式在延伸，所以你知道這就是2008年以前也深信金融商品所造成的。過度信用擴張的他，其實是同一筆債權或是同一筆資本，但他不斷地透過這個方式，他就可以分紅。分熱就很多事，他可以創造很多的利潤出來。啊。衍生性金融商品就是一個無中生有的東西。所以。非常跑步，也非常的厲害啊，如果。我個人認為是如果懂得真的覺得哇，那個真的是fast money啊，就很快塊錢啊，就是他可以不斷地延伸，因為。衍生性商品本質上是可以沒有限制，特別是在格林斯潘當美國的聯準會主席那個時候，因為他是學忘記她是什麼出身，他基本上非常放任。金融機構去發展各式各樣的衍生性金融商品。Non在他的那個當那幾年的時候，基本上就是美國劃界市場化這個，這是股票跟那個這個年翻好幾倍的那個時代都有，所以每個人大家都是賺得這個分紅賺到不行啊。不過，很快的喔，就是基礎證據，如果崩塌，那就會連帶延伸到後面的衍生性金融商品的鼓勵的分紅分寸，那這個是我們跟各位簡單談第2點好，很快的第3點是這樣。他一樣，他就是本法第8條第二款所稱中華民國境內之合作社或合夥組織營利事業所分配之盈餘，是指依合作社法規定在中華民國境內設立登記之合作社所分配之。啊，所以，就是依我國的合作社法設立登記的合作社，所以他其實跟第2點的一我國公司法設立登記公司所分配的議員，他都是準據法啊，都是準據法好，只要是一營利事業的股利盈餘，原則上是依者俱法，可是因為獨資跟合夥，那麼理論上你只要是一商業我國商業登記法所設立登記的。獨資跟合夥，那他也不會是他發放的股利，與他也是屬於中華民國來源所得，可是沒有設立登記的，在這裡面，只要你經營地點在中華民國境內，才有可能是中華民國來源所得，這個時候就要跳過去去適用。第8條的第9點規定啊，第九款規定就是經營的。因為你沒有準據法的第一款跟第二款，那你這個時候就要跳過去去適用第九款的規定，你的經營地點在中華民國境內。經營地點在中華民國境內，這樣才是屬於中華民國來源的手段，而這個第8條的第九款規定回來，對應回來的對應回來，在這個所得來源，這個來源所得認定原則裡面是他的第10點第10點。第10點本法第8條第九款所稱在中華民國境內經營工商農林漁牧礦冶等業之盈餘指營利事業在中華民國境內從事屬本業營業項目之營業行為，包括銷售貨物及提供勞務所獲取之營業利潤。所以。你沒有一所句法。那只要你有實質經營本業的營業項目的營業利潤，你的經營地點營業行為的經營地點在中華民國境內，這個時候就是中華民國來源的苦力盈餘中華民國來源的發放股利盈餘的這個所得來源地好，這個是我們。透過啊，對相關條文的解讀跟配合，這個來源認定原則，這個來源所得認定原則去做解讀的好來，然後因此我現在我們就一一地，我就以假設各位手頭上有這樣的一個要點，有以這樣一個要點認定原則考試是不會考啦，我也不會這麼不上道的考這種很無聊的考試啊。但是我們學習還需要知道，背後他到底是什麼原理原則啊，就這樣而已。所以我雖然很清楚的告訴各位，不會考這種無聊的考試，但是我們總是要有一些準據法，這個也是各位在將來你不看這個來源認定原則，但是你在腦海裡面大概知道說，哦，他可能會有哪些標準？ 可能會有哪些標準好，那我們第一類的股利所得，原則上我們剛剛就跟各位講，一準據法就是一那國法這一套標準，我跟各位說，他其實是美國的標準，美國就適用準據法，這個我在前面，不知道是哪一次上課的時候跟各位講過，美國基本上是按你按哪個州法的設立的，你就是那個州的公司營利事業，這個是美國式的標準，一直向德拉瓦州，我有跟各位去講過說。在美國，不管你事業做多棒，在東岸西洋做得棒，很多公司都跑去德拉瓦去，依該州的州法去設立營利事業，所以他們那個州法裡面有怎麼樣的組織形態，原則上。當他發生爭議的時候，就回到德拉瓦州去訴訟啊，這個就是都各位在公司法裡面常聽到的德拉瓦州的法律，那你只要是以美國的法律設立的，在臺灣的標準裡面，這個就是北商。這就是外國公司依我國公司法設立的，原則上，這個就是我國的境內的營利事業，這個的標準原則上是刑事標準。相反的。所以歐陸法系的國家，他們比較會用不是形式標準，而是用實質的經營地點在哪裡？ 實質的營運地點在哪裡？ 法國德國歐陸法系國家比較偏重用實質的像愛爾蘭，其實也是用實質營運的為標準。那因為我們用形式準據法。這個時候很容易讓人們去產生規避之可能，所以我現在只要一外國公司法設立我在臺灣做境內分公司臺灣分公司，根據我剛剛跟各位念到第2點的第二句的規定，我在臺灣賺的錢。會回去給國外的總公司。不算中華民國來源所得哦，所以OK，他只需要他用外國法設立，然後在臺灣作為分公司的組織形態，原則上他只就境內也就是中華民國來源所得顆一次我們的所得稅，然後他把盈餘課完以後的盈餘要匯回的時候，這個不會再課稅。不會再被第2次歌稅。那會回到他自己所屬的國家地區的時候，他是用英屬維京群島法設立的英屬維京群島不可所得稅。所以這個時候他就能夠實際上有效地降低稅。也就是相反的臺灣的臺積電，他在全球的手段，他是依中華民國公司法設立，所以他在臺灣賺到的錢，他在美國賺到的錢在歐洲賺到了錢，他全部都要。原則上都要算我們的營利事業所得稅。只有在你在個別國家被人家顆所得稅好根據我們剛剛念到那第3條第二句的規定。從外國來源地所得被外國的稅捐接機關課稅的，那麼你就拿著那個納稅憑證，經我國駐外的使領館或認許的機構去做認證以後，哎，你就可以拿來做外國可扣抵稅額，稅後稅額扣抵，這個就是總機構在中華民國境內他全球範圍內的所得家外國可控的稅，但原則上你必須是外國來源，經過該外國的稅捐接機關。做過課稅沒有課稅的話，原則上你的外國客空，你說還是一樣是零？ 你會全部都歸入中華民國所得稅法去科中華民國裡面的營利事業所得稅，這樣有問題，我們大致上的課稅的結構是這樣好。那如果在這個情況底下裡面，我們的這個這個這個我們的稅法裡面規定，就是你依照我們的公司法設立的，那你就是總機構。在中華民國境內，全球來源所得都要課稅，可是如果你依照外國法設立的。特別是設立臺灣的是分公司的話，他是美商的臺灣分公司，或者是英屬維京群島臺灣分公司，那麼原則上就是臺灣分公司只在臺灣課一次，營利事業所得稅。然後盈餘匯回的時候就不用再課稅。這樣有沒有問題？ 他的稅負差別就差在這裡，所以各位可以。去看一下實務上有多少公司是這樣？ 首長，你可以去看一下有多少公司用這招方式順利的就可以把盈餘欸，你要注意哦。臺灣分公司只就臺灣來源所得課稅而已，喔啊不就美國或歐洲的賺的錢，因為他在我們的稅法裡面他叫。非稅籍企業。她非我非我國的稅籍企業。他只就臺灣地區來源所得科我們的所得稅哦這樣聽得懂嗎？各位可以聽得懂嗎哦，在這種情況底下，他就可以把美國或歐洲的所得全部想辦法，不用課到所得稅，他只就臺灣的所得臺灣的所得，他跑不掉，他基本上會被課一次。我們臺灣境內來源的所得課一次所得稅，那這一個課完以後，她再把那個盈餘匯到他自己的境外公司哪一家境外公司位在一個。名不見經轉，而其實也不能說明，不但是一個租稅天堂地區租稅天堂的這一些VI開賣，或者是巴拿馬這一些被認為是租稅天堂的地區或國家車，那麼這個時候因為這些地方基本上不課所得稅或者所得稅負極低，這種情形底下裡面他實際有效的稅負，他可以在全球賺了好幾百塊，臺灣只有100塊，在美國賺500塊，在歐洲賺600塊。全球加起來，他本來是1200塊，可是他只有就臺灣的100塊刻了20塊錢的所得稅。所以他的實際有效稅負就是1000二。啊，那個20，那個。20出1000二。他實際有效稅負是多少？ 20÷1200。有沒有百分之一？ 都沒有。你看，一個正常企業在臺灣要繳20%。我光設一個準據法，我就可以只剩下不到百分一。繳稅的是笨蛋。繳稅的是傻瓜，那麼愛國。不知道什麼叫做這個叫實際意義，這就是為什麼。好制度本來就是。荒謬到極點的本來就是對真的比較有錢。因為你薪資所得沒有這種勞動，沒有沒有辦法，這樣晃來晃去，可是我要做生意的話，我用外國法，我就可以有效地把盈餘利潤留在海外，你為什麼不做？ 做生意本來。實務的操作，這個現象你說清楚，知道你就會越知道哇，那我們的稅負。雖然以想像真的是這樣，可是在政治上要動，真的不是太監。就跟我們到處都是。夜市裡面的攤販，我不知道各位是怎麼看的，但我沒有特別的意見，但。德國這一段這一段時間開始要耶誕夜，是因為他們持有耶誕節前這一段時間，有開這種耶誕夜是那為什麼他們不把耶誕夜市常態化。就像我們臺灣一樣，每天都有夜市，只是分不同時間。他就是一個城市的管理各項機能的思想，他才會產生到處都是優勢第一個。人家正常開店的要有一個店舖經營，夜市不用，只要一個地方化解。第2個。環境管制規範排水規範僱傭條件規範勞動管管制的規範，然後課稅規範全部都放在一邊的，這個就是夜市。

，我，我只是跟各位講理論，各位不要，就是如果剛好各位的身邊周邊的親朋好友是在夜市裡面工作，我沒有貶低的意思，我完全沒有貶低的意思，我都會覺得你賺錢是好事。作為稅法老師，只有一件事情。你賺錢了。請你繳稅。這應該不算過分。我自己認為。不想要繳稅就是很過分，那如果是這樣。我也沒我我不沒有什麼，我只是跟各位講，在臺灣做到這樣一個。方式確實是不太容易，我知道政治上有很大的困難。就像我之前我來跟各位講一下，居住正義不是那一次流行那幾個人上去，他們根本搞不清楚，就是這裡上什麼回事。弄不清楚為什麼居住正義。我說實在話，那個真的就很典型的political的那一種講法，那個根本就是搞不清楚狀況臺灣的居住正義，他單一這個環節，他沒有辦法透過，用一個什麼政府把售價降低就好了，你知道政府售價降低會整個基本上受傷的會是現在一群中產階級，擁有不動產，他真的會整個崩塌，是整個的秩序上的崩塌，一個這樣的民主國家都不可能這樣。都不可能像你那些上去去講的那樣子看。我只能跟各位說，稅制裡面有很多不合理的現象，但。怎麼去做起？我確實作為稅法老師，我也不敢跟各位講，依照我的方法一定能做得到，不是因為我就不是獨裁者啊，不是說了算。民主國家，他必須要透過很多的稅負。這個說服他首先是必須要有很多人認知到這個問題。他並且意願去改。民主就是這樣。沒有捷徑，也沒有比較遠的路就是這樣，因為他就是必須要透過說理，說服的前提是先認識到問題的存在，我們現在的問題是連認識到這個是問題的存在。都不一定，正因為如此，很大程度上我們很多人自己也並不知道，我們的稅捐負擔是長這個樣子。這個是這個課程，我自己個人認為很需要，特別是法律背景去多了解這個領域裡面的。我當然知道一天改變不是，而這個改變不是一天就能做成，可是完全沒有認識這個才是比較大的問題，也許改變可能是。老師已經死了好幾10年，好幾事情，但只要有認識，他才會有真正改變。Non以我自己當學生的時候，到時候的人炒地皮算正常啊，我沒有拿來用，就算剛好而已啊，這個你可以講，就是這個是本來就是，應該應該是這樣講的哦，那老師你開公司這麼好用，你為什麼不去開對啦？就是有些，我雖然知道我不會去做啊，因為這個這個還是有不同的，你也可以說老師就是因為你可能沒錢啊，所以你就不會去幹這種事情，也也不完全是這樣，但我知道確實是這個一個方式，如果我把我變成是一個臺灣分工。但是的話，報我的稅負就變成只有1%而已啊，當然重點是要你賺錢。開公司不是目的，開公司的目的就是要賺錢。這是真的開公司，明明就是要賺錢啊，為了要賺錢，他才會有繳稅的問題，如果你真的是虧損，在老師的立場，虧損就要求認列進去。有所得就要課稅，這是半句話，有虧損要準予減除，你不能只講前面，後面就不講。所以你講我前面我是一個右派講後面的我看起來變左派。不是這樣，因為你話不能講斷面，就以這樣一個方式去說這件事情的時候，也希望各位能夠在此同時了解我們稅捐那個法治國家我們的弱點，或者是我們的問題可能會存在哪。好，我現在很快的把幾個要點裡面啊。第4點，第一項規定，本法第8條第三款所稱在中華民國境內提供勞務之報酬，於個人指在中華民國境內提供勞務所取得之薪資執行業務所得或其他所得。哦，你看哦。這個第8條第三款所稱在中華民國境內提供之勞務。他這個地方，這個於個人是同時。適用三種類型的所得就是薪資。執行業務所得或其他所得啊，也就是一時性的勞務所取得的所得，然後於營利事業則指以下之情形。以下下列之情形，提供勞務所取得的報酬好第4點的第一項第一款的規定提供勞務之行為，全部在中華民國境內進行，且完成好OK這個地方，他才開始終於出現幾個我認為比較關鍵的字眼，叫做你的進行跟完成地點在我國境內。進行跟完成地點在中華民國境內，這個就叫做營利事業所取得的勞務的報酬是中華民國來源所。可以嗎？好你的勞務的進行跟完成，那我個人的理解是，這個就是勞務的實施地點在中華民國境內。勞務的實施地點在中華民國境內。所以我以剛剛那個例子來跟各位說一下，假設。臺北市政府。啊，假設他在香港假設了啊，因為這個這個例子，我只是隨便舉一個例子，臺北市政府在香港有個快遞，他想要去蓋一個一個特特殊的建築，然後開放給全世界的建築師團隊來招徠，來招募他來進行該項工程，其實這個也不難舉例啊，因為我們早期臺灣有很多農耕隊在國外啊，比如說拍到沙烏地阿拉伯去，在當地需要做建築的時候。我們有一各勞務的提供受領跟實施地點，這3個都有可能會主張自己是屬於所謂的勞務的取得地點，也就是取得勞務的經濟成果的課稅來源地所得的。提供的就是指，比如說是美國建築師團隊，他取得這個案子。那美國美國國稅局會主張，因為我的團隊去取得你境外來的時候，你可能是在三區的阿拉伯所做的建築工程嘛好，那這個建築工程是因為美國的建築師團隊去標到取得的案子，所以我們是勞務的一各提供者，這個地方因此享有他的課稅。另外，第2個是，欸，我們是。這個這個這個勞務的計畫的一個勞務的計畫的受領者，因為是我們去開啟這個國際標的。那也因此中華民國在這個地方就取得一個課稅的權限，跟主張那勞務實施地點的沙烏地阿拉伯也可能會主張，欸，你的勞務就是在我境內啊。我在我境內所構築的，雖然你的業主是中華民國的政府。雖然你提供勞務的是美國的團隊，但你勞務實施的是在沙烏地阿拉伯境內，那這個時候就有可能。沙烏地阿拉伯會主張是在他境內進行及完成的，好依照我們第4點第一項的第一款規定就是只要你全部在中華民國境內進行跟完成，這個就叫中華民國來源所得，所以他的標準是以勞務實施地點作為判斷標準，好第2個提供勞務之行為。需在中華民國境內境外進行，始可完成者提供勞務之行為。你只要進行是在境內跟境外都提供的話，那這個也叫中華民國來源。第三款的規定提供勞務之行為在中華民國境外進行，但是經由境內之中華民國個人或營利事業之參與及協助。好這個地方終於出現了一各實務界人人嘴巴常講的勞務，要有我國境內的個人或營利事業的參與跟協助，只要有我們的人參與跟協助，這個就讓中華民國來源。實務界幾乎判斷勞務的所得來源地就是指有沒有我們境內的個人或營利事業的參與跟協助。有參與跟協助，這個就讓中華民國來源所。正是這個條文，我告訴各位，只要有我國人的參與跟協助，即使我們不是一個勞務的提供的主要那一方也不是受禮坊甚至勞務，實施地點都不在我國境內，我們也自己認為我們有課稅主權，而且根據我們的第4點第一項的第三款規定，這個地方是中華民國難以形成，還不認為是外國可扣抵稅額可以扣你的外國來源所得喔，是中華民國來源所。這個條文規定，基本上大幅度擴張我國課稅權限所及，而且基本上否定了外國可扣抵稅額的適用。可講白一點，就是因為以我國的。角度來講，我們認為這是中華民國，你只要裡面有任何一個中華民國的個人或營利事業去參與或協助這個勞務，就算是中華民國來源。這個課稅範圍畫得可真大。真的非常大。也因此，你在實務上面這一種大大幅度擴充自己本國課稅主權，從自己國家的角度去考慮這種租稅的情況的話，我們這個是一個蠻典型的情形，而且是違背了真實嚴謹的。因為屬地只是屬地原則，確實讓所得來源地國享有課稅權限，可是不能夠，本來是屬地，本來應該是在當地有一個所謂跟當地的課稅權限，因為當地的課稅權限，國家提供給你當地的基礎設施，提供給你當地的這個各式各樣的行政上的便利，讓你因此在當地取得經濟成果，從而當地才取得一個課稅權限的屬地上的連結。結果我們的法律規定是，只要有我們的整個餐飲就協助，這個就叫狀況。這樣的一各廣泛，而我個人認為是廣泛而無邊際的課稅，其實是牴觸國際租稅法上的真實的。可是這只是我個人的說法，因為實務上每天都這樣。只要司法機關一天不廢掉這個所得認定原則，他繼續用這個標準，那這個就是我們的實務操作。話說回過頭來，法官如果不按這個標準差一點跟協助認定，那請問法官又要用什麼標準？ 這是法官的困難。法官之所以我今天我曾經想過我要是法官為什麼不大膽的宣告我不用這個所得來利潤裡面？ 因為我不用這個又沒上過柯老師的稅法。我真的不知道要怎麼用，因為我看所得稅法第8條第三款規定，他只有講。哎，這個第8條第三款是說所得來源地的那個是用。境內提供勞務這樣什麼叫境內提供勞務？ 實物說，只要有中華民國個人跟營利事業參與的形成，這個就叫境內提供苗栗看起來好像。也不能說沒有道理啊，因為我們的格貢獻嗎？哈哈。所以這樣就叫做中華民國境內。可是這個其實。跟屬地連結的那個。那個是不顧的。了解我的意思嗎？你的土地連結人家國際租稅法裡面的常設機構就是至少要超過6個月以上的年紀。你都猜有沒有協助？ 就直接說啊，只要參與一下這樣就有了，這也未免太過大幅度的擴張我們的課稅所。沒有錯，國際租稅法大家都會想辦法去做自己的課稅主權和研究。沒有錯，但是至少要有一個最低限度的真實連結。要麼死了，要麼鎖定鎖定鎖定要有一段期間得繼續性的存在，這就是常設機構的概念。德國是這樣常設機構，原則上就是要辦理以下工程的常設機構要更長。因為工程本質上就是一段時間裡面。繼續性存。他們可以透過雙重租稅的協定，甚至是放棄對那些常設機構境外常設機構的科學。可是屬地連結要建立在一定期間裡面的繼續的存在。單純只是偶衣，偶然性的參與跟協助。不構成屬地的連結，這是我們的租稅法跟別的國家。不太一樣，也是因為這樣，我個人認為我們的租稅法非常的不國際化。沒有跟國際規則準則走在一起，我們是倚靠兄弟個人獨獲創見之本。我們自己關起門來。因為是所得來穩定，所以要求你付錢給對方，你就要救援控制，所以倒楣的是誰？ 因為這個是中華民國來源所得對不對？所以假設他是美國的建築師團隊。臺灣要付錢給美國建築師團隊，他要求臺灣的。機構要就源扣繳，你不就源？ 就。獨立稅罰你的錢。所以打沒最後面，還是我國的營利事業？ 話說回來，我們在這麼不利的稅法。我們還有這麼強的國際競爭力，還有真的蠻讓人喜出望外。真的不太知道，哇，我們怎麼這麼這麼厲害好棒喔竟然在這麼不按照國際規則走的這種現況。還有這麼強的競爭力，這一點。到目前為止也是不太明白。臺灣廠商這麼厲害，可以有這麼強？ 全球趴趴走。可能有另外的方法節稅這樣也許。就大致上是這樣的稅制規則的合理化，


我相信是稅捐法律者。重要的公法上的債務，這個是在這裡面最後面跟各位提到，誒，我時間上來不及，那下個禮拜我會在借用前半個小時的時間，把所得稅法第8條的規定，我會把幾個重要的基準原則把他說出來，比如說。不動產，只要跟不動產有關，一定是不動產的所在地，因為涉及領土主權的部分。跟不動產有關的，所以像財產的租賃財產交易所得還有農林漁牧礦業。各位還記得我講農林漁牧礦業跟大自然界第一次產出，所以第在哪裡那個地方，原則上有屬地連結。我們下個禮拜跟各位去講，國際租稅法裡面的幾個重要的這種連結的原則所的連結，其實他有一個標準，基本上這5個標準下來，我們的規則會比較清楚，也比較知道到底應該怎麼做，連結不是一個參與協助我們就這樣就連結了這個是跟各位先做一點簡單的補充中，我們下個禮拜就這個部分再花半個小時時間跟各位去做一下講解，因為之後率先課題之後。就進入稅基。稅基才真的是考試上的重點啦，因為稅基比較容易考試啊，這個是對各位說一下，我們先到這裡。