# 20231023_01

---
課程：1121所得稅法一
日期：2023/10/23
周次：08
節次：1
---

包括相關的一些問題來。在上個禮拜，我的類型裡面，我們透過。一個所謂的勞務的投入或是資本的投入，那原則上他們應該都具備一個，繼續一段期間內才能獲得。那個財產上增益的這個類型特徵啊，所以。透過所得的勞動力勞務的投入，或者是這個。資本的投入。Bing繼續性的特徵。是資本的投入。上個禮拜跟各位提到一個獨立勞務跟。非獨立。獨立性的勞務，這個的分類。那么在以他的。現在的勞務關係來做一個分類的標準。乘現在的勞務的分配。我們講現在。合法。跟雇主？ 所做的給付這個是所謂的薪資的所得的類型。那么以過去的。過去的，然後依法律所提煉的。依法，而不是只有合法而已，他必須依法有限制的體驗。那么在他容許的她法律規定的範圍內，裡面所取得的這個我們把他稱之為叫退休所得。獨立性的勞務，這個部分我們把。農林。分出去，我們把職業所得。分出去，我們再把營業所得。裡面作為工商農林漁牧礦冶啊雖然稱之為工商農林。好了，反正各位以後有這個各位在工商農林漁這個農林。從大自然界裡面的第一次產出，包括土地產出的。農。零。土地裡面有一種類型，包括土地的礦產。然後大海跟河流，海跟河流。這個叫漁業。夜。好那大自然界的動物動物。動物。這個叫木啊。大自然界的第一次產出第一次產出。這個地方雖然有農林，但他是這個的加工。第2次。即使這裡面，他有一個類型上的分類，是原則上不改變物資本質的加工，簡單的包裝還可以算在農。但。改變其物資本質的加工就不再是農林業。即使他本身不改變木質，如果本身是做一定程度上的配合混合，他也可能會被我認為是農林業，各位，能夠知道這個差別嗎？當然，因為這個地方，他其實是一個第一次產出的直接從。大自然界裡面的不管是土地山脈河川海域誒，這個動物啊，裡面的產出的啊，這個都是數。啊，農民所。Non屬於工商農林漁牧礦冶，這個看起來雖然也還是講這個東西，但他原則上是作非物理的加工，跟過於複雜，被認為是。變更其本質性質的加工類的這種調整組合，這個時候就會被認為是一個所謂的一般營業行為，裡面的這個農民業者。那么職業，我們在上個禮拜跟各位講過，他是三重的組合，一重是四大私。那是大師，只是一個類型的描述特徵啊，他主要是在講他是一個經由某一種大學或學院的職業養成加國家考試的組合。第二種是人類智慧財產權的表現，這個特別是透過精神創作所產生出來的，作詞作曲作文啊作家誒？ 啊。藝術表演的各項類型包括這個表演人在眼，自由業的這些作家作者，那么，專欄作家類似這一類的全部都是第3個是特殊技藝的。工匠啊像這個經紀人跟這個特殊職業技能啊，這裡面當然如果不是進入職業，就會是一般的農業啊，對不起，對就一般的營業，因為我們在這裡面的工商這個部分，而其實如果他的職業類型，他其實毋寧比較是偏向於獨資跟合夥，因為如果他是屬於公司組織的。公司。合作社。跟有限合夥一有限合夥。成立的組織型態這一個區塊就會進入到營利事業課徵原則上課徵營利事業所得稅。原則進入營利事業所得稅的稅捐主體的範圍。當然在這裡面有交界的領域啦，因為這裡面是一個獨資跟兒。我們在民國86年以前，他是全部都是營利事業所得稅，因為獨資合夥跟公司合作社跟那時候還沒有出現的有限合夥，他基本上就是獨資合夥公司合作社，他基本上是營利事業的不同組織的形態，86年以前的所得稅對獨資跟合夥是最不利的，因為他們原則上被課了兩次稅捐，當時候是25歲課一次75歲，再來加75塊，再來乘以40%，所以他等於是75+40到。47283。等於是25+30，他是55塊錢的稅負，他等於稅後進所得只有剩下45塊。86年以前是這樣。80六七年開始到民國107年之間，我們兩稅合一的制度，這個時候他是消弭了，特別是獨資跟合夥的。這個。重複課稅，因為他只剩下對個人的營利所得的課稅。但他造成了非獨資合夥，特別是一般。組織型態利用公司合作社他在課徵稅負上的極大的依從跟激增成本上的負擔，也就是那個兩稅合一的設算所得稅額扣抵帳務。設算扣抵稅額的公司帳戶，對特別是公開發行股份的公司來講，因為他們的股東本來就是一直不斷的在變化，在我沒有所謂的基準日之前，我基本上還是一直可能在變化的過程當中裡面，從而他造成了上市櫃公司一個極大的一寵，我們稱之為叫依從成本上的負擔，因為公司為了要設兩稅合一的扣可扣抵稅額帳戶，那他一方面很大很大的成本吶。為了要避免超額分配盈餘。又做了一個可扣抵稅額帳戶的可扣抵稅額比例的分配，也就是當年度你原則上可以被扣你的稅額，指在那個限度，也就是要分配給自然人股東的那個盈餘限度範圍內，你們去做課去做課稅，但你如果是做過度的盈餘分配的話，這個地方他有限制的規定，也因為這個限制的規定，造成了一方面是國家稅收短收，因為本來87 6年以前，我們是兩稅分離的。對。公司營利事業所得稅來講，他等於是錢階段的稅收，我們收不到後面到個人營利事業的時候啊，登記個人股東的時候，我們才會有到所得稅，然後為了防堵大家又不分配盈餘，在這種情況之下，我們又加增一個在其他國家稅制裡面沒有了，所以他會變成一個只課真未分配盈餘所得稅，但實際上我們有所知的大量稅收有增加高度的依從成本。其大的徵納雙方爭議的關於可扣抵稅額的比例，從而我們終於才在107年的時候把他廢掉，廢掉以後現在留下一個尾巴，就是這個地方改變城市，公司課徵一次的營利事業所得稅現在是20%，哪公司如果發放盈餘，也同樣是公司的，我們再也不課稅，因為扣第14，12條的規定我們就不課稅，那只有在公司。繼續分配盈餘給自然人的時候，我們才對自然人再去，那一次的個人的所得稅。但原則上透過用分離課稅28%，或者是做稅額扣抵8萬元額度內的。複雜的稅。這就是我們現在的2歲的合宜的這個制度的本身的演進的過程，那留下來獨資跟合夥呢則是用一套。在德國稱之為叫做兩重計算的方式，在臺灣沒有一個正式的稱呼，所謂的兩種計算就是營利事業這個層次的時候，先算一次他的營利事業所得。但不課稅。然後第二重的計算則是按照他的股份就直接分配盈餘給獨資。資本主跟合夥事業合夥人。所以他是第一從這個營利事業所得稅這個層次裡面，他只有做賬務上的計算營利事業所得，然後按個別的合夥股東的股份在第二重計算裡面，就直接認為他已經把盈餘分配給合夥人，然後計入他個人的。營利曉得他呢？所得的類型是屬於我們的，待會我們講的那個營利所得的類型就是鼓勵與的分配，但旅遊下一個尾巴，在我們所得稅法第7條第二項裡面說，在這裡面獨資3號跟合夥事業還是要做營利事業所得稅的申報只是不用繳而已，他的繳稅是到了他們的股利盈餘分配給。自然人的股東，因為他就做了第2道的計算，鼓勵你的計算，從而把那個營利所得就直接算入。都是資本主或股東啊，那個合夥人的個人的營利所得來。繳納綜合所得稅就好啊，他是兩道計算，但是申報這個階段仍然不合理，就是營利事業所得稅還是要做申報。71條第二項有做了一個。很偉大的外溢的規定是，但如果你是小規模營利事業，則不用申報，我幫你算。一個。德國制度裡面簡單的穿透稅制，在臺灣是分2個階段，然後做申報稅的不同處理，也就是說原則上你還是要報，但小規模營業的營利事業不用抱我幫你算啊，所以這個地方是再算的申報這個這個強制裡面就是那個激增程序的協力義務，上面來講有申報跟有不申報的，但都不需要講什麼時候繳，直接就算出個人的營利所得。以個人綜合所得稅的方式去繳納。這就是我們偉大而無法所起。不知道要不要玩什麼，因為到目前為止，目前為止也沒有一個正式的一個名稱的稱呼去說明這件事情，也就是關於我們的這一種。穿透性的稅制裡面的這個獨資跟合夥商號啊。OK，我透過這個圖形，基本上把牢固所得的各種類型，可以把他用這個分類圖把他涵蓋，然後接下來資本的類型透過股本。資本也就是我講的資本是在講現金通過。跟。債權？ 5本，如果他是。實體物。動產。不動產。以及無體財產。那個。如果你各位要分類，其實還可以再分類下去，無體財產還有分成那個受法律規定保護的臂形，諸於特別權力的專利商標。跟。製作全還有一種是法律上所保護，但沒有辦法跟那個企業做分離的。這一種包括營業秘密商譽商譽這一類本身在性質上面來講是一個無體存在的，我透過把資本做各種不同類型股本，對不起這個地方孳息。尤其我忘記執行怎麼寫？ 各位知道。常常講到一半的時候，突然秀逗。立德。孳息的本體是股本，讓你產生的是鼓勵。盈餘？ 孳息的。股本是通貨或者是債權？以上個禮拜有一個同學剛好來問我，通貨是一個國家發行的法定貨幣，你可以把他理解成他是持有者對國家的一個債權的主張，這樣各位可以理解嗎？美金等於是我對美國政府的一個債權主張，美國政府要擔保我在市場上對市場上實體物的購買力，所謂的通貨膨脹，就是這個國家發行出來的通貨，本來是作為支付工具，但他無法有效的購買。他先前所承諾的那些事禮物，這個時候就叫通貨膨脹，相反的就叫緊縮。講清楚嘛。新臺幣羅氏新臺幣是對中華民國的一個請求，確保他在市場上實體物購買的實質的這個這個購買力的一個憑證，所以基本上債權是通貨的衍生性商品。在詮釋通貨內在新產品。今天我如果把我借給你錢，我把他拿去做有價證券，話變成是在資衍生性金融產品，這個就是衍生性金融商品的類型態樣，我可以再繼續，我可以做swap做交換，我對你的再跟你對他的在我們2個10萬做交換，然後我再把他去做。有價證據的話，就再把他發行出去，這個就是。衍生性金融商品的概念。回到我們這裡面，股利盈餘這個地方，如果你的資本類型是通貨獲得，是通貨衍生性出去的債權的話，原則上你取得的都叫利息。動產不動產，你取得了都叫租金。我這個地方要做這個分類，是因為我今天第2個小時要跟各位去講所得來源地。因為這個圖形待會會用，所以我先掛在這裡。第3個無體財產無體財產的話，你取得的就叫權利金。也就是把使用權讓與給他人因此去收取的孳息。如果你的財產本體不管是哪一個，你去做轉售價差的，這個就叫財產交易所得，財交所得在我們的的。哼，你把第9條規定。OK。所以臺語上個禮拜跟各位講，即係以他因為他又可以賺孳息就可以專利的，但你人只有兩隻。因為你勞務只有一天24小時，所以我同透過這個圖形，我就告訴各位一件簡單的事情，找好工作不一定是好事。有本事。老錢？ 跟銀行撈錢出來，你賺價差的這個叫資本利得賺孳息差的。就是你的支持，所以人永遠跟不上錢的速度，所以資本家們是用錢去賺錢。啊，我們傳統的教育告訴你。應該要找好工作，好好的努力的學習法律。說穿了，也就是這樣。法律上對。同樣是所得，但做不同對待，我們今天跟各位從這個地方再開啟，另外一個可能性叫一時性。一時性，意味著他是一種偶然。機會才機會偶然，遺產稅也被認為是因為你爸爸死掉被繼承。所偶然留下來給你，我們不能預測誰死亡，但是他死掉的時候突然留給我的，但我在這個地方，我先暫且跟各位去描述一時性，在我們的所得稅裡面有三種類型的一時性的所得，第一個是一時貿易盈餘。哼。第2個是第八類的機會中獎。競技競賽及機會中獎的。三各校第十類的其他所得。OK這三類都是偶然機會發現偶然機會才發生的一時貿易盈餘，他本身就告訴我，一時性，我上個禮拜有跟各位講過誒？老師的職業本業是教授，但我也有一個一時貿易盈餘，因為我在我家的上面裝一個。太陽能光電板啊，就是那個太陽能光電板，你如果去德國去看到現在目前很多家庭製造，然後他們上面的那個房屋上面那個本來以前都是做那個什麼鋪，那個鋪那個不管是鋪什麼東西，現在很多都是啊，改鋪成太陽能電板就這樣，其實我們臺大如果有興趣的話，搞不好可以在我們頂樓上面鋪一個，那很多公益大家現在都是用這個租給人家。然後就可以收錢。他是一個創造收益的一個，一個收入來源都是這樣啊。所以要透過規模經濟的方式的話，他可能這樣整個飛機這樣過去的時候，整個臺大一片全部都是那個太陽能光電板大概是這樣好，我在我家裡面上面裝了一各這個這個我賣電給臺電，這個叫我的一十棒硬盈餘。我不是以之為業。但我兼差愛店，好像看出來我後面我不是教授，我是賣店的，但我們這樣講，我如果。經常性麥片。我賣的規模不是只有我家頂樓，我去你家去學校去農場，我去到處去搜，上面去蓋這個太陽能光電板，我就會從一時性。變。繼續性。然後如果我自己去做這個生意，這個是獨立勞務裡面的。哪一個？ 營業所。看的懂嗎？ 類型化的功能就是幫助各位整體掌握區分彼此你我。這個圖請各位。帶在腦海裡面。你就永遠不會忘記所得的類型，其實是根據繼續性一時性，這也是我現在跟各位講為什麼所得。我們不適用所謂的市場經濟活動，而對不起不適用市場經濟活動的那個所謂的源泉理論，因為源泉基本上是掌握之息跟勞務。源泉，你有只掌握孳息跟勞務，他資本利得就沒有掌握，所以我們的所得稅法絕對不是才源泉理論。相反的，你可以講就是說我們是繼續性一時性，而且我們的勞務裡面不管你是在是在私的事業，或者是在公領域裡面服務，只要你付出勞務的，基本上都是所謂我們薪資所得所掌握的公私事業職工裡面的薪資所得的範圍，所以我們也不是全然採取所謂的市場所得理論，我們是把公私領域裡面的包括你的。這個各式各樣的這一些勞務提供或者是非勞務提供非勞務提供OK，他就有可能是來自於其他所得。來自因為我們的薪資所得的類型，只限於現在合法雇主提供的，如果你是一時之機會利用植物工作之機會看到顧客的錢包，突然就想起來哦，原來我可以把他偷走。竊盜。不法的和不法的行為，利用職務之機會收取的回扣，利用職務之機會所賺取的公務員收取的賄賂。他就會是其他要不要喝水，答案是要只是不是原來的心之所，就這樣而已。做不同類型的歸類，他會幫助我們去比較同跟不同，當然一個我個人認為是，也許這個地方獨立性，然後不需要分那麼細。啊，應為農民職業跟營業，其實他是營業的特殊變化特殊類型而已。他是大自然界的第一次產出或是延伸的加工性商品，乃至於特定的職業類型的一種特定的形態，基本上差別在成本費用差別在勞務的提供規制管理上又會有不同規定，但是對稅來講，我們看的是錢，我們不是在看工作管制規定，從而對稅來講。錢才重要，這裡面因此重要的區別標準叫圖利器。而為鼓勵行。何謂努力性是這個差別，我在上個禮拜跟各位講過，我是傳奇叫老師，我平常在職業做律師，他那時候在端午兼差的時候，他還是一個執業律師，今天你上法庭賺到的報酬，這個叫執行業務所得，可是你今天到了東吳大學去授課，市售東吳大學的只是告訴你幾點幾分到達你上什麼內容上課的內容，儘管是你的專業。你可以去自由發揮，決定你要告訴學生的內容，但你仍然是受東吳大學的，只是換言之，收不到學費，你不會減少你。也不會多1分，也就是不管盈虧都不減少，其報酬給付資本值，從而。陳清秀老師，她從東吳大學取得的叫非獨立性勞務的心之所。當同時間可以執行律師業務。所以一個律師到學校演講。他會有兩種手軟，一個是他職業的。自行用手，一個是。那個心之所。這個是如果我們正和兩種類型都可以比啊，所以我在考試的時候就可以考這個，我讓各位去比較不同類型，因為這就是區分差異理我。好一時性，裡面包括一時貿易盈餘，其實一時貿易盈餘，老師有一位學生寫的碩士論文就是一時貿易盈餘跟營業所得跟財交所得這3個的。營業所得。才交跟一時性貿易。我舉例而言，我舉例而言。我賣襪子。你不會今天我賣襪子三雙，你就認為我賣襪子。我有取得所得，一時貿易盈餘了。不會吧，因為賣襪子以他的伯利的這種本質特性，一般來講，連稱之為一時貿易，都很難認為是一個某種程度上的這一種，持續透過這個行為去獲得。所能所以賣三三化子？ 叫財產交易所得。我自己去跟人家境的，比如說這樣子好了，三雙襪子。但我一時賣，一直賣一直賣。在某程度上就會開始進入。一時貿易。然後之後。越慢，生意越大，就會變成是。營業。像各位清楚嗎？ 賣東西看客體，所以在德國賣房子。你一年賣移動算不算營利事業？ 要看客體。我是只看頻繁度這裡面講的繼續性跟一時性啊。基本上是看客體價格跟他交易的性質上，哪一種平凡性的可能賣三雙襪子不會讓你變成營利事業，但一年賣三棟就會讓你變營利事業。因為他高檔講。德國有一個叫5年3個客體界線。他是跨年度去觀察一個人從事該項行為的頻繁跟密集性，被稱之為叫繼續性的勞務。所以什麼叫我連3個課題你一年賣移動？雖然不構成立刻就構成所謂的這個營利事業賣房子的營利事業，但你5年內賣三棟以內。還是財產交易所得？ 5年內任何一個5年的期間，只要超過三動以上。第四段開始，你就會。量變變質變讓你變成是一個營利事業的手段。從而變成是德國法制裡面被稱之為叫人合性的營利事業。一樣還是透過兩重計算，但他就會變成是一個營利所得的類型，而不再是單純的財產交易所。這個叫。類型特徵這個每一個概念都叫類型概念。因為他是有邊際界線的差別實務的有趣就在這裡頭，對不起實務的複雜。沒有一個全然絕對的標準，而是。中和整體觀察。任何兩類三類，我都可以把他湊齊。去比對。那就看各位。期中考試嘍。這是。一時貿易其實一時貿易與是一個老師，到目前為止沒辦法給各位明確界限，因為他不能以之為主業，但又不是單11次性的財產交易轉售價差。到什麼程度叫一死貿易盈餘？我跟各位舉個例子是我賣電，你可以想像我賣顛不是以之為主業。那我現在舉一個例子，我是一個醫生，然後我非常喜歡日本去日本旅遊的經驗。非常多，所以我就在我的部落格裡面開始去寫日本旅遊經濟經驗的這一些分享分享分享到最後面，有些人說啊，柯醫生一定會帶我們去日本做一個日本團旅遊啊。禮拜哦好，那我們就來做日本團吧嗯，但這日本團是這樣，嘛就是買機票10張有送一張啦就簡單來講就是，大家一起出團啊，大家都買一張機票啊。航空公司會有一個喇叭。叫做折價哪這一張折價就送我的？ 這樣可以嗎？ 沒問題吧？幹嘛跟著我去日本玩吶？ 所以在這種情況底下，那個折價你獲得一張免費的機票，算不算你有所得？ 有所得到哪種類型？ 奶粉。有趣版啊，這是實務案例哦。實務的案例。因為不同手的類型。成本費用認列的問題。哪一種類型會有對應的？ 成本費用。認列的極限。證明方法。所以即使我們是綜合所得，我們仍然很大程度上會需要分類。OK，這是第一個。機會中獎一時貿易與還有其他所得裡面最典型的叫賭博的收入。他們都是繼續性的，對不起一時性的機會，中獎不會以之為遠，但如果基本上還真的以參加各地舉行的競技競賽。為他的目標，藉此賺取獎金跟報酬的。還真的有可能轉成。以之為業，所以在德國。一次玩撲克牌，這個叫。一時性的所得在德國是完全排除在課稅所的範圍內因為他們認為十賭九輸。原則上你應該是所以我乾脆就不算入所得的範圍。所以用這種方式把他切出去課稅所的範圍，所以你去那個拉斯維加斯去拉霸那個在德國，你賺到錢都不算什。虧損也不給你認命。德國人的做法就是把他從一時性繼續性切開來，只有繼續性的活動才是課稅。這種射悻性一時性好聽一點叫一時性。難聽一點，叫射悻性很高的這種。中獎的這一種，這種不管是合法或非法，原則上在德國被稱之為。是好？ 不列入課稅所得，按。嚴格的把他切割開來，因為德國人認為有所得就要課稅，但有虧損要權利解除。不準，做半套。美國人比較長。做半套的話也可以，但是只有賺到錢的才算所得，虧損不準你。盈虧目的。我們的會稅法就超美國的，受美國影響就是說OK，如果你是有賭博行為，那。有所得。併計綜合所得課稅，但有虧損不足以減除。我們的做法是這樣，那因此一時性是所得稅的所得，從而我國不產源泉理論。我們是採純資產增加說。不管是繼續性或一時性，或者是採跨越市場所得理論的營利所得，我們原則上只要賺到錢都會被認為是所。不管你的行為來自繼續性一時性合法性或非法性都是一樣，都是所。哎呀。只是他歸類為哪一種類型的差別而已？透過這個地方，儘管是這樣的一個我還是要把一些排除在現行的課稅所得範圍的部分跟各位作說明，財交所得我們排除掉土地的財產交易所得105年以後排除掉房屋跟土地的財產交易所得。改課房地合一稅。讓各位可以嗎？ 財產排斥土地，因為土地改課土增稅，105年以後排除掉房屋加土地的房地合一稅。第2個是財交所得排掉證交期交的財產，交易所得釋字一條4至2條，這個地方我們不刻才這個證交期交的交易所得稅，所以透過這個立法的圖形告訴你，立法者告訴你要炒地皮要炒股，賺的錢都不用課所得稅好棒棒，這個就是我們立法者鼓勵大家做的事情。

你這個地方，不管你投入多少的勞務薪資，所得者永遠是最上面這一個。所以收入跟成本費用被認列的最柯的也是最沒有機會去做核實課稅的稅負所得類型。越往下的包括利得裡面的證交期交跟房地產的部分，臺灣向來就沒有做實質核實的課稅。所以，要以為立法者多公平？他在鼓勵各位炒地皮跟炒股，就這樣而已。我們不評價，因為他在稅制上是被有利對待。有意對待我們，大家理所當然推想他應該是受國家鼓勵的行為。第一次聽到，但我跟各位講，現實就是如此，也沒有。好。第2個部分，我們把一時性的所得，裡面的因為爸爸死掉。偶然留下來的遺產跟贈與拉出去分離課稅，所以遺產跟贈與爸爸生前，給的是贈與爸爸死後給的叫遺產。爸爸不管生前給贈與死後給都是一時性機會性的所得，沒有違法的問題，他是合法性的，那這種所得為什麼要分開來？簡單來講，就是怕一時性加進來。累進稅率級距升高就這樣而已。好，我們對一時性所得，也把其中某些類型以變動所得的名義把他拉出去做部分免稅部分課稅，也就是變動所得的一半，課稅一半。這個免稅，所以也是從這個一時性裡面啊，這對不起，自從繼續性裡面只是因為他是累積多年所的一次大量實現，從而向農林所得啊。像漁業的一次出海打漁，累積多年所得會透過變動所得的態樣，把他做部分的課稅部分的免稅啊，這個是我們現行的法律規定所稱所稱假出來的。分類所得的類型，哪也以這個方式來跟各位做一個基本的說明，這個結構我們待會留著，因為我們接下來要跟各位去講所得的實現時間跟所得的實現地點，這個部分有具有。要按照所得的類型去做實現特別是時間跟地點的。一對一的判斷，我們待會兒再進一步做說明先休息一下。