# 20231120_01

---
課程：1121所得稅法一
日期：2023/11/20
周次：12
節次：1
---

期中考試的，第一題是關於，所得稅法2條一項關鍵適用的稅捐主體，這個。這個第一題的第一小題適用的稅捐主體，基本上就是我國的所謂的境內居住者。的個人啊，它它的相關的條文規定在，第2條第一項以外，那就是在第7條那個地方那，適用的。稅捐主體是境內居住者，或者我們也可以稱之為叫我國的稅籍居民。啊關於是，這個只就境內來源所得來課稅的立法理由的說明啊，這個是不是符合量冷冰的課稅原則？那從。這個全部所得全部課稅。原則來看，他並不符合這樣的一個，量能課稅的基本原則底下的一個子原則，也就是全部所得課稅原則，這個也是，我們在所得稅法的這個條款規定上面來講，比較不符合量能課稅原則之處。當然，我們在民國95年，在2006年的時候，我們訂了一個所得基本稅額表意的規定，算是在一定程度上將。這個全部所得的部分啊，就是境外來源所得，我們透過用所得基本稅額條例的方式去補充，去做課稅，因此。在這個地方誒？ 以所得稅法跟所得基本稅額條例整體來看的話，確實在這個限度範圍內，裡面也就境外來源所得去做課稅，但即使是如此，我們並沒有將這個量能課稅原則裡面，特別是境內境外來源所得應該要同等對待的，這樣子的一個基本精神，也就是平等課稅原則的精神裡面去做平等的計算稅負。那這也是我們即使是看到所得稅法跟所得基本稅額條例這樣的一個這個課稅的原則來看的話，我們並不還是沒有符合量的課稅原則，實務上的考量確實他認為，有幾個理由，關於境外來源所得不易控制，關於工業化國家的稅率比我高高，所以課稅也不會難以增加稅收，有沒有增加？ 稅收並不是在這裡面，立法者自己去考慮的，也就是說，簡單來講不是稅捐增收入增加，所以就可以也不是稅捐收入收不到就不可以唔，你應該考慮的是稅捐負擔的公平性的問題。也就是說，作為我國的稅籍居民，理論上他應該要去就境內境外來源所得都依照法律的規定。來去做稅捐上的申報所以，在這個制度全部所得課稅原則底下裡面他法律上就應該要有相同的規定，讓納稅人去做稅捐上的申報，因此對所得來源不易控制，以及難以增加我國稅收，這個並不是一個正確上的一個考量，這個全然基於我國的稅捐稽徵程序上面是否能控制，以及對。稅收是否能增加作為考慮？並不是，在稅捐立法上面的一個，這完全正當的一個考量，在稅捐立法上面來講，仍然必須要以這個為前提來做稅捐立法上的課稅。簡單而言，就是對我國來源所得不易控制。這一件事情其實在目前的實務上面，也順帶透過這個方式跟各位說到這個地方，原則上是透過所以就資訊交換的方式去獲得，這個境外來源所得的相關資訊，然後對所謂的工業化國家的往來，所以我們並沒有課稅的質疑，這一句話也不成立誒。作為國際上的往來，並不是只有工業化國家而已，那它其實也有相對稅率，對相對我國來講是比較低的稅率的國家，那當然在這種情況底下，不是以所謂的稅收增加考量來作為他，這個頻段上的依據，這個是對第二題原則上提到全部所得課稅原則。那即使是有考慮到所得基本稅額條例，我們並沒有符合稅捐負擔的平等原則的這個考慮。哪？這是第一題第二題的話則是稅捐監機關依照檢舉的資料查得的某甲在同一個年度內買了10筆的預售房屋。跟。這個，預售了房屋的這個權力的這個證明，那么這位某講在這一段時間內把這10筆的紅單轉讓獲利。

好第一個小提問的問題是，誒？稅捐機關查得這個轉帳紅單的獲利之後，除命補繳稅款以外，有給予應繳稅款而未繳稅款的裁罰，這部分是不是構成了一行為2次處罰？ 

本題的關鍵在，補稅並不是裁罰。補稅是一個不利的一個制裁性的行政處分，所以補稅同時並裁罰並不構成所謂法治國原則底下的一行為2次處罰，這個是蠻普遍對非稅捐法律人被誤解的一個道理，認為補稅就是一種裁罰，那因此第二題的第一小題。稅捐監機關對納稅人未申報營利所得所做的。補稅跟裁罰的處分並不構成法治國原則違反的意行為2次處罰。補稅是根據稅捐負擔能力所做出來的計算，換言之，有所得理論上就應該要繳納申報來負擔應負的稅捐，因此補稅是量能課稅原則的維護是一種確實是對納稅人構成一個不利益的。金錢給付的負擔義務，裁罰則是屬於對過去行為的非難，也就是你應申報未申報。應做誠實的申報而未做申報，因此第二題的第一小題不構成意行為的2次處罰。


第二題提到甲主張紅單買賣，那麼這裡面特別涉及到土地的部分，是不課徵土地所得稅，這個是非常常見的一種抗辯的方式，也就是納稅人主張，根據我國的所得稅法的規定，所得稅法第4條第一，這個第一項第六款的規定，土地是不課徵所免納所得稅的所得，從而他是不用申報，那因此我既然沒有申報這個，本來就很正常。本件個案，他其實是預售屋的買賣。換言之，在這裡面至少就預售屋這個部分，他本身是一個權利的買賣行為，他並不是一個所得稅法第4條第一項第16款所講的土地，包括即使是土地，他是一個土地移轉登記請求權，所以第二小題的題目，他其實在實務上，它是一種權利讓你。就算是以不動產的土地違標的，它仍然是權利那名。這個是第二小題裡面的對於實務上，當事人往往主張土地出售本身不課徵所得稅，沒有錯所得稅法4條一項16款。屬地土地的出售不課徵所得稅，但他的性質並不是免納所得稅的稅捐優惠。他其實是跟所得稅裡面，因為跟土地增值稅，他避免重複課稅，因此他並不是一個稅捐優惠的規定。話說回頭，這個地方並沒有土地的移轉的問題。預收仍然是一個還沒有建築完成的房屋，所以它是一個權利的，讓與實務上對以往這種紅單的讓與基本上就是以權利讓與為。有來做稅捐上的核課，從而構成了。他是一個權利這樣與的財產。交易的手段基本裳這個是對一二題的第二小題的這個部分喔，就是關於對此沒有所得稅的申報義務，他主張的是土地的不動產的這個轉送，那其實這裡面只有土地，才有可能有這樣一個假抗辯主張成立的適用。但，這個不管是預售屋的部分或者是土地的部分，其實都不構成的。。這個，土地移轉不課徵所得稅，他並不是說去，因為他其實分離課稅，他只是在這個地方。無論如何，他並不構成了他是一個這一個權利得讓與的概念。因此第3個小提啊第二題的第三小題這個也構成，也就是這個是在，這個房地合一稅沒出現之前。在我們實務上對這一類的房屋，如果假設跟這個建設公司買了繼承屋的買賣的話，那這個部分會不會影響到關於當事人的所得類型的判斷？第二題的第三小題裡面。特別是關於房屋的買賣這個部分，他到底是用財產交易所得，還是是營利所得誒？ 在房屋財產交易買賣裡面一次性的。一次性的交易行為會構成的房屋財產交易所得。但是在一段時間內的密級連續的交易行為，會讓這個行為變成是一個營利事業的營業上的行為。簡單來講，就是透過整體觀察綜合評價的方式，一個人在。單11個年度內買賣超過10筆以上的。就算是繼承房屋，不會再次財產交易所得。而是一個經常性繼續性的一個參與市場交易行為，從而他是一個。營利所得的太陽，也就是第一類的營利所得，我們以往在紅燈交易裡面基本上也是同樣的看法，買賣紅單本來就是一個權利，讓與他本身是一個財產的，就是一個財產上的交易行為，但你如果在一段期間內不斷地去做買賣，那這個就會構成了所謂的營利所得，也就是從第，第6頁第七類的那個財產交易所得會變成的是第一類的。營利所得的概念，也因此，這一類的行為以往在實務上面來講，他是構成第一類一律所得以營利事業的方式去做課稅。因此第一二題的第三小題一方面涉及到關於稅捐客體的類型判斷，當然他也會因此連動影響到對稅捐主體的判斷，也就是這個人會變成從個人的方式，變成是一個營利事業，這個是在實務上面，在我們法定合一稅沒有出現之前啊。原則上我們在所得稅裡面的這個課稅的方式反覆不斷買賣交易行為。構成了繼續性，正因為它的持續性地繼續性的參與市場交易的行為，讓它變成是一個營利所得的態樣。這是在第二題的第三小題裡面第二題第三小題裡面。在德國實務上有一個看法啊，叫做5年3個課題界線，但不寫到這個沒有什麼關係，因為老師只是借這個案例跟各位去說。對於買賣的標的物本質上是。做整體觀察綜合評價要看那個標的物本身，他是不是有這樣子的一個，就是原則上你要已知經營。作為一個營利事業的營利目的，如果賣三雙襪子，他不會構成一個營利型營利，所謂的繼續不斷的營利行為，因為本身畫質的單價並不高。但是房子的單價是比較高的，也就是說在這個地方，德國的實務上發展出對一個營利一個人，他有沒有構成營利行為？他是。跨年度去觀察一個。行為人是否在一段期間內任何一段5年內。只要賣三棟方式，以上第四洞開始，就會被認為他是一個營利事業。這個叫5年3個客體界線，但這個其實回過頭來就是。整體觀察綜合評價的意思，賣三雙襪子即使在一個年度內賣三雙襪子，不會讓你變營利事業，因為襪子單價低。但賣三棟房子就會讓你變成營利事業。也就是你賣一次。一年內賣一次啊，兩年內第2次再賣，3年內第3次在賣的4年開始，如果假設你有在賣了第四棟房子，在德國實務上就會構成了營利事業，換言之，你的本來是房屋財產交易所得，他會變成的是營利事業的營利所得干預營利事業所得來計算。哥說，因為正常來講，不會有人一天到晚都在。用房屋來作為他的一個買賣交易的行為，當然很多人都會說喔，房子切進去，我租進去，這樣就是這個也是一個對一個社會上的一個實體經驗。觀察，他確實不是在實務上面啊，不是形諸於文字的一個判斷標準，而而不是形諸在法律條文裡面的一個判斷標準，它是由司法實務所發展出來的。那臺灣在這個地方早期實務上一直都沒有很明確的標準，甚至，實務上流行一個叫做一年6個客體啊，也就是當你一年內只要不賣超過六戶就被認為不適。營利事業不課徵營業，因為房屋是要課營業稅的喔，所以就不課徵營業稅，你就不會課徵營利事業所得稅，那這個客體的這個一年六戶的界線，即使是以本件這個地方來講，他也是一年賣超過十戶以上。所以啊，這個在我們的實務上面來講，也會認為是一個營利試驗，那會同時該當了營業稅的申報繳納義務，也會有營利事業所得稅的申報繳納義務，簡單來講就是。一各行為人會因為它的市場參與行為的對一個課題的反覆繼續性的參與，讓他從這樣子的一個個人的性質，而轉變成是一個以繼續<profanity>性</profanity><profanity>經</profanity>常性的參與市場的經濟活動，而變成是一個營利事業的性質，這也是我們在這裡面營利事業啊。營利事業跟個人之間在稅捐主體上的差別，一個人而言的話，個人還會是。這裡面他獲得營利所得的一個判斷上的一個標準，從而第三第二題的第三小題涉及到客體的判斷，那也涉及到主體的判斷，以德國跟臺灣的實務上，基本上都認為他是一個營利所得，不過當然我我想很多個個案事件裡面，也有當事人會主張認為說我這個這個這個你繼續性的判斷標準不明確，對沒有錯。啊，因為正是因為整體觀察綜合評價，所以這個確實會存在著不確定性，就算是以5年3個客體為界線，那是不是買賣山東房子以內就不構成營利事業第四週就突然變成營利事業，對沒有錯，他確實在實務上會有產生這樣一個，我們這樣講量變變質變的道理量變變質變啊，你不斷地這樣子去做，從客觀上他才有辦法去評價，已是一個營利事業。持續性繼續性的去參與市場上的活動哪？即使構成了個人，他也會從他財產交易所得第七類的所得變成是第一類的所得的類型啊。這個是啊，藉由這個實務上的案例也跟各位去談，這個是實務案例啊，因為老師出了這個題目，其實是從實務案例把它變換出來的，那這個是在房地合一稅沒有出來之前，房地合一稅1.0版出來，民國105年之後。預售屋的買賣就已經被列入法定合一稅課稅的範圍，所以目前的法制啊。目前的法制房地合一稅裡面原則上會把預售屋的買賣以他的轉售價差檢調土地增值稅的稅基，然後其餘剩餘的所得額就改顆法定合一稅。所以我借個案發生在100年度啊。他那時候並沒有房地合一稅啊，那當然也許同學們會，這個假設你有特還特別另外再寫法律才會在。配合一些沒有關聯性，他因為在發生了那個年代裡面，主要是紅單的權利，讓你的行為，那你權利讓你的這個法律規範來看的話，他本身是一個財產交易所得。它原則上一次讓與財產交易所得兩次，讓與財產交易所得到達一定的程度，上面一年內的10次讓與比較清楚而明確地被認為是一個營利所得的態樣，這個是。跟各位去。說明跟這個這個實務上的觀點，我個人也認為這個看法是正確的，雖然確實他有。存在著不確定性，就是繼續性跟一次性的買賣交易行為。其實，買賣交易的行為跟一時貿易盈餘跟經常性的營利所得，他本來就具有很高的不確定性，就是那個界線是不太清楚。一時貿易盈餘跟經常的營業行為的那個。那個經營的那個行為跟。偶一為之的這一種。一致性的買賣交易行為，他確實是存在著有不確定性的問題，這也正是在訴訟實務上或犧牲實務上面各位作為法律者常常會面臨到我體個案裡面，必須要去做綜合所販賣的個體市場上的單價以及他交易的實務的現況的一般情形來做判斷。我剛剛舉的三雙襪子不會構成一個營利事業，因為。襪子單價不高，你再怎麼賺，不太可能以之為業，不太可能只是11年賣三雙襪子，所以你賣三雙襪子會是11時性的財產交易所得，好在這裡面原則上比較是屬於偏向財產交易的。英語，但一年內賣三棟房子就有可能，當他第四洞出來的時候，就有可能就會變成了，是所謂的營利所得的態樣，那這個是我們跟各位談到第一題跟第二題，我們在上個禮拜舉行的期中考的部分還沒有看各位的答卷的內容啊，因為，這個之後還要再另外花時間打改看考卷啊，但是先至少每一次考完試以後，我名字上都會先檢討一下老師的。這個問題的方向跟答案大致上給各位做參考，也歡迎各位同學，如果你自己寫題目的時候，你有不太一樣的想法，也可以這個，老師搞改考卷，我總是要有一個一個一個特定的方向。特定的方向，那這個特定的方向來作為一個評分評價的標準。哪？如果各位同學在個別的答題裡面啊，你覺得你自己是很有理由跟說服力的，也可以來個別表示你的意見，我沒有特別的，就是一定非得非得要照剛剛老師所說的這樣的一個做法，不過你要有具有充分的說服力。確實是以老師主觀的新增為基準好，所以原則上你可以來表示你有什麼樣的看法不同的意見，那，老師會聽聽看你的說法，是不是可以成立那假設假設假設你真的不能說服我哪，其實說實在，我必須跟各位說，答案並沒有一定要非得照老師的。因為訴訟就是這樣。我也許我在這次的看法裡面比較偏向國稅局或是他犧牲實務司法實務的看法，但你也可能採取不太一樣的看法。其實改考卷只是用一個答案去做衡量標準，那那個答案未必是真的是標準答案。未必，真的是標準答案，因為。某種程度上，他確實是會有開放性，因為這個開放性，所以基本上老師並沒有一定非得要以我個人的答案作為標準，我只能最後面跟各位講，如果你不能說服我也沒有關係，那只是以老師的標準，你沒有達到這個標準而已。但歡迎各位同學未來在稅捐的訴訟實務上可以提出你的觀點，你只要能說服法官，你個案還是可能會贏，就只是這樣而已啊。把這個確實它存在著有價值，因此它會有一些。結果的開放性歡迎各位同學，也希望各位同學能夠不是因為老師講的，所以你就覺得只有這種思考的方式，也希望你有不同的思考的結果的方式出來，這個是法律在價值判斷底下的結果上的開放性。這個是給各位做參考。因此我們的減少最大，這裡有問題嗎？ 沒有上課上提出問題也沒有關係，以下客人再來題也可以，因為我們今天有進度，所以如果假設各位沒有問題的話，我們接下來就來繼續談好我們在考試之前跟各位提到的好，我們稍微簡單的回顧一下啊，我們整個法條的規範結構第2條的規定啊，他基本裳區分的稅籍居民跟非稅籍居民。第2條的第一項是稅籍居民，也就是境內居住者，原則上它只就中華民國來源所得課稅好，那如果在中華民國來源所得課稅底下，根據兩岸人民關係條例。稅籍臺灣的稅籍居民就是戶籍設在臺灣的稅籍居民，而原則上它是就臺灣跟大陸地區來源，所得全部都課中華民國來源所得，所以他是所得稅的所得。第2條第二項的非稅籍居民，也就是非境內居住者，那這個非境內居住者，原則上它也是就中華民國來源所得課稅，但他的課稅申報的方式，或者是繳納稅款的方式，我們今天會跟各位去講，因為我們的繳納稅款方式有兩種，一種叫結算申報。二甲第一項的稅籍居民原則上用結算申報程序。2點第二項的非稅籍居民則是用就源扣繳程序就源扣繳程序，因此。我們回顧一下我們前面講的稅捐主體稅籍居民跟非稅籍居民。我們的法律規定，原則上它全部都是就中華民國來源所得課稅啊，當然這個中華民國來源所得的中華民國的概念，根據兩岸人民關係條例啊，是指臺灣跟大陸地區，只要你是戶籍設站臺灣地區，那原則上就是臺灣大陸全部都叫中華民國來源所得，那至於港澳跟境外（真正的境外：美、日）這個就源完全都不是，也是不可所得稅法上或所得。他是改課所得基本稅額條例的個人所得基本稅額。這個的，我們的所得稅法啊。由於做了這個徵原則上只就中華民國來源所得課稅，所以他的區分實益主要是在季增程序上面，他不是實體上稅負，在所得稅法這裡面，因為所得稅法裡面只就中華民國來源所得課稅，所以居民跟非稅籍居民都是只就中華民國來源所得課稅只是。所以他的實體法上，他沒有什麼差別，他的差別主要是差在稽徵程序上面啊，因為我們的所得稅法的第2條第一項啊，他一樣是就中華民國來源所得課稅。但是。他是按照所得稅法規定的。結算申報程序依本法規定來做課徵綜合所得稅，這個是第2條第一項的規定。啊。第2條第二項非稅籍居民除本法另有規定外，其應納稅額分別就來源扣繳。所以我們今天。第2節開始，我們會跟各位去談關於結算申報跟就源扣繳程序，但講，今天稍微快了一點點啊，可能下個禮拜啊，可能下個禮拜第2條第一項的稅捐主體啊。他在，他的區別實益上面啊。一般如果以德國跟日本為例，或者是美國為例的話。只要是稅籍居民，原則上是全球來源所得課稅，也就是都是顆同樣一種稅法上的所得。那我們的所得稅法比較特殊，我們只同樣都是只就中華民國來源所得課稅，那差別是差在它的機身程序上面2.1項的稅籍居民事業按他依本法規定，他沒有寫什麼叫依本法規定。Non解釋上是一本法第71條的結算申報規定來課徵綜合所得稅。那么，第2條第二項的規定則是除本法另有規定以外，分別就其應納稅額來做。這個就來源扣繳，也就是依照就源扣繳程序來做稅捐的季增，所以我們的稅捐主體主要的區別實益。被認為不在稅捐的實體法上，而是在稽徵程序上面，以所得稅法的規定來看好我們，繼續把我們的稅捐主體這個脈絡稅捐客體的規定在我們的現行所得稅法裡面對所得是沒有定義的。我們是透過所得稅法的第14條的十類的所得。去。定義出應課所得稅的所得的概念。所以我們在這裡面有十種類型的所得，當然其他所得的類型，這個短身條款規定就是一個涵蓋性的綜合性的是一個網羅性的構成要件的規定，原則上你只要可以分類到前面這九類的話，那原則上就不會進入其他所得的第十類的所得。那么，在第14條的規定裡面，除了第14條規定的應課稅所得，我們還有第4條的免納所得稅的所得的概念，第4條第四之一跟四之二。這一些事概念上，他是應稅所得，可是是免納所得稅的所得，換言之，是提供要不是分離課稅的所得，不然就是屬於稅捐優惠的所得，也就是說，部分的所得確實是被免除掉的，比如說是之一四之二的證交期交的所得，他是一個被認為並不構成所得稅的所得。他是另外以其教證交來替代的，這個所謂的所得稅啊，就是用交易稅來替代所得稅的課稅啊。當然這個部分，導致個人是有很強烈的反對的意見啊，這個地方，依照目前實務的看法，四之一跟四之二是以其證交期交替代證所期所。哪老師個人看法是交易稅不能替代所得稅啊，雖然立法者自己這樣講，以立法者的邏輯來講，他認為這個就是一個分離課稅，因為他就是用證交期交來替代了證所跟期所啊，這個是四4-1、4-2、4-3條的規定啊。

4-3條的規定。公益信託的免稅要件的規定信託課稅的部分，我們會留待到關於信託就是遺產贈與稅的時候，我們再來去進一步去談啊。

信託課稅原則上信託的財產移動並不是所得的概念，它是一個設定信託行為的財產上移動，所以這個地方4-3條的條文規定他本質上也並不是一個市場經濟活動所獲得的所得。4-4跟4-5條的規定，原則上我們跟各位提到是房地合一稅，我們留待到所得稅法四的時候，再跟各位去談。

關於這個部分，他當然是所得，但問題就是我們有第4條的第一項，第16款的免納所得稅的所得，所以他是第4條的第一項16款之外，我們有另外4-4跟4-5，又是4條第一項16款的例外。

從民國105年開始，2016年開始，我們又在4條一項16款之外，另外加徵了房地合一稅。

所以我們這個地方的法條結構是，所得稅對於不動產土地的移轉，免納所得稅，改課土地增值稅的稅負，然後我們在105年開始又再把這部分的稅負又再把它拉回來，改課房地合一稅。

這個地方有立法上的價值的轉變。

根據第4條第一項第16款規定，免納所得稅所得。但同時間我們考慮到有土地增值稅的課稅，所以它是一個分離課稅的概念，但從民國105年開始，我們把這部分的分離課稅的土地增值稅的這個部分，把不動產交易裡面的所有的剩餘所得，又再以4-4、4-5條的規定，再把它拉回來去課徵房地合一稅。所以這裡面有一個立法者的價值轉變。

那我們4-4跟4-5條的規定，我們原則上到所得稅法四的時候，再跟各位去做說明。4-3，我們到所得稅法三再跟各位去做說明。


第5條的第一項的規定，是關於物價指數調整啊，這個是免稅額的物價指數調整規定，理論上他應該是放到17條，因為17條才是免稅額規定的所在。我們的立法者的立法技術，是把這個部分拉到前面來做規定。5條一項本應該要放到跟17條第一項第一款講免稅額規定的地方。他跟你講，這個地方要按照物價指數去做調整。

這個地方我跟各位簡單說明一下，免稅額不是只按照物價指數調整，根據生存權保障的憲法保障的這樣一個要求，立法者應該要與時俱進的調整免稅額，讓他可以符合當代維繫物理生存的最低需求。因為我們的免稅額立法上是6萬，所以每一年每一年調整，基底太低。那個6萬基底太低。那麼如果基底太低，每年物價指數的調整基本上就不太容易去反映出納稅人維繫物理生存需求，也就是衣食溫飽這個部分的物理生存需求。

他是立法者透過生存權保障以及我們在105年所增訂的納稅者權利保護法的規定，這個基本生活費用不課稅原則，其實也是在反映維繫物理生存需求跟社會生存需求的這個全部額度。這個額度應該回過頭來，變成是第5條第一項，在法律解釋適用上的一個重要的，立法者應該要維持與時俱進的這樣一個數額的調整義務。這個是5條第一項的規定。5條的第二項規定是稅率的規定。綜所稅稅率的規定。從體系上，他應該是在應稅所得的計算之後，就是，稅基之後，是稅率規定，所以他法條規範位置會是在17條之後。稅率的位置應該是在17條之後。

稅率放到前面。他只是告訴你一件事情，我們的立法者基本上都是財稅背景，不是法律背景。就這麼簡單法條規範的位置，其實按構成要件去區別，他是主體客體稅基稅率稅基乘稅率得到稅額構成要件這樣一字排開來，他這個才是法律邏輯的思考。
那因為我們的財稅背景主導的稅捐立法，所以他們認為稅率最重要，你去看我們的所有的稅法規定，稅率都放在稅基之前。充分表彰出我們的稅法。從財政部體系一直到送進立法院裡面，基本上都是財稅思考。他們認為稅率最重要。

但從法律觀點來講，稅基比稅率更重要，因為稅基不對，稅率承稅基只會得到更不對的稅額，尤其稅率是累進稅率會扭曲稅捐負擔的分配，所以。第5條第二項的位置，這個是一個累進稅率，我們稱之為叫超額累進，我們是5個級距的超額累進稅率的設計。5個級距分別是5%12%。20%30%跟40%啊40%，那其實我們在。民國97年之前，我們的那個稅率，其實他是第一個級距是6%。接下來是13%，接下來是21%，第4個是30%，第5個是40%。早期的我們綜所稅的累進稅率，他就體現出所得越高稅率越高的概念，因為第一級是利用percent。第二級，43%。13-6 X7。第三級是21 21檢13是吧？ 第四級是30-20億。X9。第四級是40-30億-34 10。所以各位理解我們早期的立法者的思維邏輯嗎？ 第一級是六%，第二級就加7到13%第三級加8到21%第四級加9帕到30%，第5級+10%到40%最高這個就叫邊際稅率，這個叫邊際啊，因為他就到Lancer就是，就是我最高就到這裡，我沒有在上去啊，沒有在上去，所以我們的最終所說的。最高邊際稅率是40%我們是五階五階第一階本來是六，後來將一遍五%，本來是13，第二階，然後將一遍12%，然後本來是這個這個。21將一%，所以我們在，上一次修正的時候，把這個稅率各自在第123這3個機器人的時候各加一%，那主要比較高的30%跟40%就沒有將。但他原先的設計是67+7+8+9加實，然后是5個級距，我們這一種叫階梯式的。超額累進稅率階梯式超額累進稅率那，德國是現行的累進稅率，也就是他每多一定的數額，他就會上一個級距，所以，比如說你第一個級距是六%，那第2個級距是6.1，第2個級距是6.2，就一直不斷地疊上去，這一種，他在那個累計稅率裡面，它就會形成一種無弧形的糊狀的拋物線式的。超額累進稅率。我們是。我們是階梯式的。這是稅基。這是稅率。我們的第一階第一階。這個是免稅額加扣除額免稅額加扣除額。從這裡開始起算，第一階，這個是6%。第二階，我們早期43%第三階是21%第四階30。第五街40。42歲，我們是五階段的超額累進稅率，所以它是一種階梯式的。德國式的是。這樣。啊，最高到42.5%。他這一種拋物線，是的，它是一個小型的階梯。看的懂嘛。小型的階梯。啊，因為小型階梯在外觀上。連結在一起就變成拋物線。所以德國的所得稅，他們沒有像我們這個階梯狀，他們是拋物線式的累進稅率，簡單來講就是你賺100塊跟賺101塊，第101塊那一塊的稅負比前面的100塊稍微要更重一點。充分體現出累進稅率，是一種社會國底下的財富重分配思想。像清楚嘛？ 沒有財富，重分配思想。比例稅率的稅制比例稅率會是這樣？ 

德國現行。他們的圖形是稅基X軸稅率y軸。這個軸線他是一樣的，叫做比例稅率，比如說20%。這樣也是量能課稅原則，因為你的所得越高，基本上你的稅負比例雖然一樣，但數額會比較高。這樣各位清楚嘛。我們這一個階梯狀或是德國的現行或弧形的這種狀態，基本上是來自於社會國原則的財富重分配，實現量能課稅的平等原則，即使是以比例的方式呈現，其實他也是符合最佳負擔平等原則的量能課稅原則。


這一種的比例，叫超額累進稅率。那因為各國美國在剛開始在做所得稅課稅的時候，就是以這種超額累進的方式。所以如果你調成這樣子，會對誰有利？ 對誰不利？ 對低所得的人不利。對高所得的有利。這樣聽得懂嗎？ 


我們限制是63，而不是52，23時50，所以假設我在稅智慧裡面，我主張，或是在立法院認為，我們這樣可不好，我們來改平等課稅原則，我們一律都用20%或28%。

好，我們現在來看一下28%。我們的股利所得，我們現在改28%。好，那個28%就是一個比例稅率。好，對誰有利？誰有利？ 賺高所得的有利，對吧？因為如果綜合所得稅，他本來最高是到40%呢？ 你本來只需要繳納5%，你用28%當然就不利啊。所以他告訴你不要去投資股票，如果你沒那個能力、沒那個資格的話，你不要去投資股票。

人家投資股票是節稅啊，他們繳40%。有股利所得用28%課稅，那這樣就對他有利。但是如果你是繳5%，你用這種，變28%，那就對你比較不利。這樣清楚嗎？

我們稅制改革方向是對有錢人。我們不用講太多意識形態，就光這件事情，請問有沒有去立法院質詢，為什麼是這樣啊？對，他實務上面其實是提供另外一種叫做，如果你可以因為二擇一啊，我們現在股利所得課稅的方式是要麼28%，要麼一個家戶所得課8萬元的可扣抵稅額，所以你就一定要選擇8萬元的可扣，你說不然的話，你本來是5%甚至20%的人，你去投資股票，你去買臺積電，臺積電發給你一張股利所得，結果你反而被高課？

啊，所以他選擇課稅的型態好，選擇就是用全部全部的所得用可扣抵稅額一戶8萬塊錢的方式，意思是告訴你說不要賺太多股利所得。你賺太多的話不掉。你會被加重稅。

這是一個我們稅制裡面的反財富分配現象。所以回過頭來就是告訴各位一件事情，研究稅法絕對對各位腦筋清楚有很大的幫助。你才知道這個社會的財富分配的方向，究竟是從貧到富，還是富到貧。你可以大致上去看觀察這整個我們的社會的財富分配，究竟在稅制裡面是如何地被扭曲分配。就這樣一件事。信不信由你，因為這個本來就是我們現在目前的情況。28%的股利所得稅率基本上是對高所得的人是有利的。


好，如果你今天是拿債券。私法。去投資債券的人越高所得人投資債券去取得債券的利息所得，他更有。但如果你只是適用5%，你去用債券這個地方二選一都沒有喔。沒有選一，就是10%，對誰有利？高所得人。

越高所得，適用40%的邊際稅率的人有利，因為他節省了稅，不只30%。

但越低所得，適用5%邊際稅率的人，他反而不利。

這是我們在稅基稅率的關係上面的反向的財富重分配的狀態。

其實本來累進稅率的設計應該是，多賺錢越多的他要講越高比例的稅率，這是財富重分配，本來在社會國原則底下，他想要的那個圖像，不過現實上並不是全案是如此。我們第5條第二項的規定，我們就跟各位談到這裡好那第，這個，課稅級距的金額第第5條第三項基本上就是反映第5條第二項。課稅急劇的金額，他因此要固定調整那這一個部分，我要跟各位說一下，立法形成空間比較大。不像第5條第一項免稅額是反映物理生存需求，所以立法者不僅沒有太大的立法形成空間，立法者有一當代社會維繫物理生存需求的調整的行為上的介面。他有那個戒密上的義務？ 相對5條意象的生存權保障規定5條二項跟第三項同樣都是在調整。稅率的形成邊際稅率有多大好，這個邊際稅率窄窄的，那他的稅率就會隨之提高喔，那這一個邊際稅率這個叫級距。邊際稅率？ 邊際稅率？ 最高是邊際稅率，這個這個寬度，這個幅度，這個叫級距。級距跟邊際稅率這個立法者享有比較高度的立法形成空間。好，也就是根據國家的。財政上的需要，原則上他去調整立法者享有比較高度立法形成空間。只有對免稅額跟扣除額所反映出來的那個數額，原則上它是生存權保障的範圍，立法者的立法形成空間，相對的應該要比較少第四項的規定則是關於消費者物價指數的規定，每一年在那個，你的級距你的免稅額，你的扣除額，每一年都是財政部在一定時間以前公布，像這一個第四項規定，那個就是技術性作業性規定什麼時間公布？ 財政部改隸自己的人。內部作業規則規定公布就可以，基本上那個不需要在所得稅法裡面公布第5條第六第五項，這個是營利事業所得稅的稅率規定，我們站綜所稅裡面我們就按下不表啊。5條之一是關於扣除額跟這個。特別扣除，我也是按物價指數調整的規定，像這個就直接放到那個扣除，我那個地方一併去做規定。


第6條呢？本法規定各種金額，均以新臺幣為單位。貨幣的規定，是以新臺幣為單位。不然是要什麼？金圓券嗎？不用新臺幣你要用什麼作爲單位啊？

第6條之一的捐贈規定，這個是放到17條的那個關於捐贈那個地方去做合併的規定就可以，所以我們大致上把前面的那個總則的幾個比較條文性的規定跟各位說。到這裡，我們先休息一下，待會我們繼續回顧，把所有綜所稅的條文實體法的部分，我們把它全部都拉出來，把它全部完整的回顧一次，我們今天要進入到關於申報程序裡面的結算申報，跟家庭的成員的合併申報程序，所以我們在下一次才會去提高就源扣繳程序。我們今天先這個中間先休息一下。